      SUBROUTINE AIRCHK(ALTMEAN,TRCKMEAN,DRFTMEAN,PTCHMEAN,ROLLMEAN)
C
C     THIS SUBROUTINE CHECKS THE TRACK OF THE AIRCRAFT TO MAKE SURE
C     THAT IT IS FAIRLY CONSTANT. OTHER CHECKS AND MODS ALSO ARE PERFORMED.
C
      
      PARAMETER (NID=296,MAXFLD=8,MAXSKP=27,MXCNT=500,DEPS=25.0)
      PARAMETER (MAXEL=80)
      COMMON /IDBLK/ID(NID)
      COMMON /AIRBRN/ ALATS(MAXEL),ALONS(MAXEL),IALTFLG
      COMMON /TRANS/ X1,X2,XD,Y1,Y2,YD,Z1,Z2,ZD,NX,NY,NZ,XORG,YORG,
     X     ANGXAX,ZRAD,AZLOW,BAD,ASNF,ACSF,IAXORD(3),NPLANE,EDIAM
      DIMENSION ALTMEAN(MAXEL), TRCKMEAN(MAXEL),DRFTMEAN(MAXEL)
      DIMENSION PTCHMEAN(MAXEL),ROLLMEAN(MAXEL)



C
C     OUTPUT SOME ADDITIONAL POSITIONAL AND ORIENTATIONAL INFORMATION
C
      IDPTR=129
      SCALE=FLOAT(ID(44))
      WRITE(*,15)
 15   FORMAT(/,5X,'SWEEP  MEAN TRACK  MEAN DRIFT  MEAN ALT',
     X     '  MEAN PITCH  MEAN ROLL')
      DO I=1,ID(35)
         IF (ABS(ID(IDPTR)/SCALE - ID(IDPTR+(I-1)*3)/SCALE) .GT.DEPS)
     X        THEN
            WRITE(*,20)ID(IDPTR)/SCALE,ID(IDPTR+(I-1)*3)/SCALE
 20         FORMAT(5X,'HEAD1=',F8.2,' HEAD2=',F8.2)
            STOP
         END IF
         WRITE(*,30)I,TRCKMEAN(I),DRFTMEAN(I),ALTMEAN(I),PTCHMEAN(I),
     X        ROLLMEAN(I)
 30      FORMAT(5X,I3,3X,F8.2,4X,F8.2,3X,F8.2,3X,F8.2,4X,F8.2)
      END DO

C
C     SET ANGXAX TO BE TRACK
C
      ANGXAX=90+ID(IDPTR)/SCALE
      IF (ANGXAX.GT.360.0) ANGXAX=ANGXAX-360.0
C
C     SET ALTITUDE OF AIRCRAFT, UNLESS USER WANTS TO OVERRIDE
C
      IF (IALTFLG.EQ.0) THEN
         ZRAD  =ALTMEAN(1)
         ID(46)=ZRAD*1000.
      END IF

      
      RETURN

      END

