      SUBROUTINE CARTAP(IPR,IREORD,ICOB,NDX,NDY,NDZ,ITOB,IDB,NST,
     X                  DASANG)
C
C        PRODUCES THE CARTESIAN OUTPUT FILES ON TAPE, FIXED AXIS OF
C                 EACH OUTPUT VOLUME IS DETERMINED BY IREORD ARRAY.
C
      PARAMETER (NMD=510,NML=10)
      DIMENSION ICOB(1),ITOB(1),IDB(1)
      CHARACTER*1 IREORD(3), IYES
      COMMON /MUDBLK/ IDMUD(NMD),IDMLV(NML)

      COMMON /UNITS/LUN,LSKP,FEETS
      COMMON /UNITSC/ IPROJ,LTAP,ISCI
      CHARACTER*4 IPROJ
      CHARACTER*8 LTAP,ISCI

      COMMON /SCAN/ ICOPLANE,IFLGBAS,IPPI
      COMMON /TRANS/ CSP(3,3),NXYZ(3),XORG,YORG,
     X   ANGXAX,ZRAD,AZLOW,BAD,ASNF,ACSF,IAXORD(3),NPLANE,EDIAM
      EQUIVALENCE (IDMUD(164),I1),(IDMUD(169),I2),(IDMUD(174),I3),
     X   (IDMUD(301),NTOB),(IDMUD(106),NLEVS),(IDMUD(175),NFLOUT),
     X   (IDMUD( 65),IBLK)
      COMMON /BYTORD/ MBYTE
      CHARACTER*8 CTEMP1
      CHARACTER*1 LAX(3)
      DATA LAX/'X','Y','Z'/
      DATA IYES/'Y'/
      DATA FTMAX/2200./


      CALL HEDSET(LTAP,ISCI)
      K=4
      IF (ICOPLANE.EQ.1 .OR. ICOPLANE.EQ.2) THEN
         CTEMP1='CO'
         READ(CTEMP1,23)IDMUD(151)
 23      FORMAT(A2)
      ELSE 
         CTEMP1='PP'
         READ(CTEMP1,23)IDMUD(151)
      END IF
C     BASELINE ANGLE
      IDMUD(158)=DASANG
         

   10 CONTINUE
      K=K-1
      IF(K.LE.0) GO TO 90
C
C        CHECK IF REORDERING IS TO BE DONE ALONG THIS AXIS
C
      IF(IREORD(K).NE.IYES) GO TO 10
      LN=2**(K-1)
      LAD=LN+K-1
      DO 15 I=164,174,5
         IDMUD(I)=MOD(LAD,3)+1
         LAD=LAD+LN
   15 CONTINUE
      IDMUD(106)=NXYZ(I3)
      IDMUD(301)=NXYZ(I1)*NXYZ(I2)
      LSKP=LSKP+1
      IDMUD(111)=LSKP
      IDMUD(96)=(IDMUD(301)-1)/IBLK+1
      IDMUD(97)=IDMUD(96)*IDMUD(175)
      IDMUD(98)=IDMUD(97)*IDMUD(106)
      IDMUD(99)=IDMUD(98)+IDMUD(106)+1
      I=((IDMUD(117)*100+IDMUD(118))*100+IDMUD(119))*100+IDMUD(120)
      WRITE (CTEMP1,101)LAX(I3),I
  101 FORMAT(A1,I7)
      READ (CTEMP1,102)(IDMUD(I),I=101,104)
  102 FORMAT(4A2)
      FEETS = FEETCL(NFLOUT,NLEVS,NTOB,IBLK) + FEETS
      IF(FEETS.GT.FTMAX) THEN
         PRINT 103, FTMAX
         PRINT 103, FTMAX
  103    FORMAT(/' +++  WARNING--  MAXIMUM OUTPUT TAPE FOOTAGE=',
     X           F6.0,' FEET REACHED AT 6250 BPI  +++')
      END IF
C
C        MOVE ALL ALPHA INFO TO RIGHT-MOST 16 BITS OF HEADER (BIG END ONLY)
C
      
      IF (MBYTE.EQ.0) THEN
         CALL HEDSHF(IDMUD,IDB,NMD)
      ELSE
         DO I=1,NMD
            IDB(I)=IDMUD(I)
         END DO
      END IF
C
C        TRANSFER INTERPOLATED VOLUME TO OUTPUT TAPE
C
      CALL OUTPCK(ICOB,NDX,NDY,NDZ,ITOB,NTOB,NFLOUT,IDB,CSP,I3)
C
C        SEND SUMMARIES TO THE PRINTER
C
      CALL IMHSUM(IPR,' ',IYES)
      PRINT 104, LTAP,LUN,LSKP,LSKP,FEETS
  104 FORMAT(/10X,'CURRENT STATUS OF OUTPUT TAPE ',A6,
     X   ' ON UNIT ',I3/20X,'VOLUME COUNT: ',I6/20X,
     X   'PHYSICAL FILES: ',I4/20X,'FOOTAGE: ',F11.2/)
      GO TO 10
   90 CONTINUE
C
C        FINISHED GENERATING ALL OUTPUT VOLUMES
C
      NST=0
      RETURN
      END
