      SUBROUTINE CHKMSG(NST,KRAY)
C
C        PRINT ERRORS -- TERMINATE
C
      GOTO (20,30,40,50,60,70,80,90,95)NST
      STOP 71100
 20   CONTINUE
      PRINT 102,KRAY
 102  FORMAT (5X,'***MORE THAN 4 RECORDS PER RAY -- RAY ',I5)
      STOP
 30   CONTINUE
      PRINT 103,KRAY
 103  FORMAT (5X,'***CHANGE IN FIRST GATE -- RAY ',I5)
      STOP
 40   CONTINUE
      PRINT 104,KRAY
 104  FORMAT (5X,'***CHANGE IN GATE SPACING -- RAY ',I5)
      STOP
 50   CONTINUE
      PRINT 105,KRAY
 105  FORMAT (5X,'***CHANGE IN NUMBER OF GATES -- RAY ',I5)
      STOP
 60   CONTINUE
      PRINT 106,KRAY
 106  FORMAT (5X,'***NEGATIVE RANGE TO FIRST GATE -- RAY ',I5)
      STOP
 70   CONTINUE
      PRINT 107,KRAY
 107  FORMAT (5X,'***MORE THAN 1024 RANGE GATES -- RAY ',I5)
      STOP
 80   CONTINUE
      PRINT 108
  108 FORMAT(5X,'***INVALID INPUT FIELD NAME SPECIFIED')
      STOP
 90   CONTINUE
      PRINT 109,KRAY
 109  FORMAT (5X,'***CHANGE IN FIXED ANGLE WITHIN SWEEP -- RAY ',I5)
      STOP
   95 CONTINUE
      PRINT 110,KRAY
  110 FORMAT (
     X     5X,'***NON-CONFORMITY IN FIELD STRUCTURE WITHIN UF RECORD ',
     X        '-- RAY ',I5/8X,'USE RESET COMMAND, CONTACT SPRINT ',
     X        'SPECIALIST, OR BOTH!!!')
      STOP
      END
