      SUBROUTINE INITAL(ICRTST,INPTST)
      PARAMETER (MAXEL=80,NID=296)
      LOGICAL IS360
      COMMON /IDBLK/ ID(NID)
      COMMON/ADJUST/INFLD(10,3),SCLIF(10,2),NIF,IOFLD(10,3),SCLOF(10,2),
     X   NOF,SCLAZ,SCLRNG,SCLEL,UNSCAZ,UNSCRG,UNSCEL,LOWAZ,IZAD,IS360,
     X   MINAZ,MAXAZ,METSPC(10),IWFLD(10),NFLI,SCLNYQ,UNSNYQ
      COMMON /FNAMES/ CINFLD(10),CIOFLD(10)
      CHARACTER*8 CINFLD, CIOFLD
      COMMON /TRANS/ X1,X2,XD,Y1,Y2,YD,Z1,Z2,ZD,NX,NY,NZ,XORG,YORG,
     X   ANGXAX,ZRAD,AZLOW,BAD,ASNF,ACSF,IAXORD(3),NPLANE,EDIAM
      COMMON /AXUNIT/ IFIXAX,IUNAXS,LABAXS(3,3),SCLAXS(3,3)
      COMMON /SCNDAT/ ELB(MAXEL),DEI(MAXEL),KDIR(MAXEL),KNDREC(MAXEL),
     X   NEL,IEL1,IEL2,KEL,KPEL,ISD,ELTOL,RNOT,DRG,NG,MAXRD,CFAC(10)
      CHARACTER*2 CTEMP

      

      DO I=1,NID
         ID(I)=0
      END DO

      NIF =0
      NOF =0
      NFLI=0

      BAD  =-99.
      ELTOL=0.4
      EDIAM=12751.273

      UNSCAZ=32.
      UNSCRG=128.
      UNSCEL=127.
      UNSNYQ=15.

      IUNAXS=1
      IS360=.FALSE.
      ICRTST=-1
      INPTST=-1
      SCLAZ=1./UNSCAZ
      SCLRNG=1./UNSCRG
      SCLEL=1./UNSCEL
      SCLNYQ=1./UNSNYQ

      CTEMP='NO'
      READ(CTEMP,77) ID(25)
 77   FORMAT(A2)
      CTEMP='N-'
      READ(CTEMP,77) ID(26)
      CTEMP='EX'
      READ(CTEMP,77) ID(27)
      CTEMP='IS'
      READ(CTEMP,77) ID(28)
      CTEMP='TE'
      READ(CTEMP,77) ID(29)
      CTEMP='NT'
      READ(CTEMP,77) ID(30)
      
      RETURN
      END
