      SUBROUTINE IPUTCP(IWRD,IAZ,IX,IY)
C
C        PACKS INITIAL POSITIONING INFORMATION FOR A CARTESIAN LOCATION
C              INTO THE LOWER 32-BITS OF IWRD.
C

      CALL SBYTES(IWRD,IAZ,0,16,0,1)
      CALL SBYTES(IWRD,IY,16,8,0,1)
      CALL SBYTES(IWRD,IX,24,8,0,1)
      RETURN
      END
