      SUBROUTINE SCNSET(KZBUF,IBKNT,IBLV,NRCBF,KZBM,IDS,J,
     X                  IND,LPMN,LPMX,KZOUT,IS360,IZAD,ICROSS,NST,
     X                  IBELOW)
      INCLUDE 'SPRINT.INC'
      PARAMETER (IDIM=64/WORDSZ)
      LOGICAL IS360
      DIMENSION KZBUF(2),IBKNT(4),IBLV(IDIM,4,NRCBF)
      LPMN=IBKNT(1)
      LPMX=IBKNT(3)
C
C     THE FOLLOWING TEST IS FOR AIRBORNE SITUATION WHERE, FOR SOME REASON,
C     THERE WERE NO GRID POINTS AHEAD OF PREV. SCAN WHERE DATA COULD BE MAPPED
C     TO. THUS, THERE WILL BE NO GRID POINTS BEHIND CURRENT SCAN WHERE
C     DATA COULD BE MAPPED TO. IBELOW WILL BE SET TO 0 TO REFLECT THIS.
C
      IF (LPMX.EQ.0 .OR. LPMN.EQ.(NRCBF+1)) GOTO 701
      IBELOW=1
C
C        LOCATE MIN,MAX AZIMUTH AND ASSOCIATED POINTERS
C
      IF(IS360) THEN
         MINAZ=IZAD*2
         MAXAZ= -MINAZ
         DO 10 I=LPMN,LPMX
            CALL IGETCP(IBLV(1,1,I),KZOUT,IX,IY)
            IF(KZOUT.LT.MINAZ) THEN
               MINAZ=KZOUT
               INDMN=I
            END IF
            IF(KZOUT.GT.MAXAZ) THEN
               MAXAZ=KZOUT
               INDMX=I
            END IF
   10    CONTINUE
         IND=INDMN
         IF(IDS.LT.0) IND=INDMX
C
      ELSE
C
         ITST=(KZBUF(J)-KZBM)*IDS
         IF(ITST.LT.0) GO TO 701
         IND=LPMN
         IF(IDS.LT.0) IND=LPMX
C
      END IF
C
      ISTRT=IND
C
   30 CONTINUE
      CALL IGETCP(IBLV(1,1,IND),KZOUT,IX,IY)
      ITST=(KZOUT-KZBM)*IDS
      IF(ITST.GE.0) GO TO 40
      IND=IND+IDS
      IF(IND.LT.LPMN) IND=LPMX
      IF(IND.GT.LPMX) IND=LPMN
      IF(IND.EQ.ISTRT) THEN
         IF(IS360) THEN
            CALL IGETCP(IBLV(1,1,IND),KZOUT,IX,IY)
            GO TO 40
         ELSE
            GO TO 701
         END IF
      END IF
      GO TO 30
   40 CONTINUE
      NST=0
      RETURN
  701 CONTINUE
      IBELOW=0
      CALL TPQERX(307,0)
      NST=1
      RETURN
      END
