      PROGRAM UFCART
C
C     
C     NOTICE
C     Copyright 1995 University Corporation for Atmospheric Research
C     National Center for Atmospheric Research
C
C This software was developed by NCAR, which is operated by UCAR and sponsored 
C by the National Science Foundation.
C
C Access and use of this software shall impose the following obligations on the
C user.  The user is granted the right, without any fee or cost, to use, copy,
C modify, alter, enhance and distribute this software, and any derivative works
C thereof, and its supporting documentation for any purpose whatsoever, except
C commercial sales, provided that this entire notice appears in all copies of 
C the software, derivative works and supporting documentation.  Further, the 
C user agrees to credit UCAR/NCAR in any publications that result from the use
C of this software or in any software package that includes this software.  
C The names UCAR/NCAR, however, may not be used in any advertising or 
C publicity to endorse  or promote any products or commercial entity unless 
C specific written permission is obtained from UCAR/NCAR.  The user also 
C understands that UCAR/NCAR is not obligated to provide the user with any 
C support, consulting, training or assistance of any kind with regard to the 
C use, operation and performance of this software nor to provide the user with 
C any updates, revisions, new versions or ``bug fixes.''
C
C THIS SOFTWARE IS PROVIDED BY UCAR/NCAR ``AS IS'' AND ANY EXPRESS OR IMPLIED
C WARRANTIES, INCLUDING BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
C MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
C EVENT SHALL UCAR/NCAR BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL
C DAMAGES OR ANY DAMAGES WHATSOEVER, INCLUDING BUT NOT LIMITED TO CLAIMS
C ASSOCIATED WITH THE LOSS OF DATA OR PROFITS, WHICH MAY RESULT FROM AN ACTION
C IN CONTRACT, NEGLIGENCE OR OTHER TORTIOUS CLAIM THAT ARISES OUT OF OR IN
C CONNECTION WITH THE ACCESS, USE OR PERFORMANCE OF THIS SOFTWARE.
C**********************************************************************
C
C           SOFTWARE DEVELOPMENT BY DOUG RHOADES (CSD)
C
C**********************************************************************
C
C        CONTROL MODULE FOR TRANSFERRING UNIVERSAL FORMAT TAPES TO
C        CARTESIAN SPACE...(NOT RELATED TO ARTESIAN SPACE OR OLY)
C
C        COMMANDS
C           INPUT   =SPECIFY INPUT INFORMATION
C           OUTPUT  =SPECIFY OUTPUT INFORMATION
C           RESET   =SET RANGES AND TOLERANCES
C           AZIMUTH =SUBSECTION DATA ALONG AZIMUTH
C           INTERP  =SPECIFIES FIELDS TO BE INTERPOLATED
C                       AND TRANSFORMATION METHODS
C           CARTESIA=SPECIFIES CARTESIAN GRID
C           PROCESS =PROCESS A VOLUME
C           RADAR   =SPECIFY RADAR PROCESSOR AND COORDINATES
C              .
C              .
C              .
C           QUIT    =TERMINATE
C
      INCLUDE 'SPRINT.INC'
      PARAMETER (NID=296,LD09P=-9999,NKOM=16,MAXFLD=8,MAXPLN=65536,
     X           MAXYZ=512000,MXCRT=256,NRCBF=400000,MAXSKP=27,
     X           IDIM=64/WORDSZ,MXCNT=500,IVDIM=(NRCBF+1)/(WORDSZ/8))
      COMMON ICART(MAXPLN),ICOB(IDIM,2,MAXYZ),IBLV(IDIM,NRCBF,8),
     X     ZRTAB(MXCRT,2)
      DIMENSION ICTAB(4),TLIMITS(2,MAXFLD)
      DIMENSION XRTAB(MXCRT,2),CTDBM(MXCNT),CTDBMXH(MXCNT),
     X     CTDBMXV(MXCNT),IVREF(IVDIM,2)
      DIMENSION C3(MAXFLD),C4(MAXFLD),IFLTYP(MAXFLD),ISIDE(MAXFLD)
      CHARACTER*8 IFLDS(MAXFLD), OFLDS(MAXFLD),NSCTP(MAXFLD)
      CHARACTER*8 FSPACE(MAXFLD),IPROC(MAXFLD),KOMM,LSKS(NKOM)
      CHARACTER*8 KRD(10),RFNAM,FNAM,P10
      CHARACTER*8 TFIELD(2,MAXFLD)
      COMMON/ADJUST/INFLD(10,3),SCLIF(10,2),NIF,IOFLD(10,3),SCLOF(10,2),
     X     NOF,SCLAZ,SCLRNG,SCLEL,UNSCAZ,UNSCRG,UNSCEL,LOWAZ,IZAD,IS360,
     X   MINAZ,MAXAZ,METSPC(10),IWFLD(10),NFLI,SCLNYQ,UNSNYQ
      COMMON /IO/KPCK(85000),KOUT(8500),IBUF(8500),NBUF(2125,4),
     X     IZ8(17),ILSTREC
      COMMON /IDBLK/ID(NID)
      COMMON /RHIS/ IRHICRS,LOWAZ2,MAXAZ2,MINAZ2,ICART2(MAXPLN),
     X     ICTAB2(4),KZV(3),IDSV
      COMMON /CFLD/NFLDS
      COMMON /CFLDC/ IFIELD(MAXFLD), INTINF(MAXFLD,3)
      CHARACTER*8 INTINF,IFIELD

      COMMON /CINP/IUN,ISKP,ORLAT,ORLON
      COMMON /CINPC/ NMRAD,ITAP
      CHARACTER*4 NMRAD
      CHARACTER*8 ITAP

      COMMON /UNITS/LUN,LSKP,FEETS
      COMMON /UNITSC/ IPROJ,LTAP,ISCI
      CHARACTER*4 IPROJ
      CHARACTER*8 LTAP,ISCI

      COMMON /FXTABL/ IFXTAB,ISKIP,IACCPT,FTABLE(MAXSKP),ITRAN
      COMMON /CRNG/ELTUS,MNBEM,RUSR1,RUSR2,RG1,RG2,DRG,NRG,VNYQ
     X             ,RNOTUS,DRGUS,CFAC1,CFAC2,CFAC3
      COMMON /CRNGC/ IRCFXL
      CHARACTER*8 IRCFXL

      COMMON /CPRO/KDAY,KBTIM,KETIM,IROV,ISWMTH,FXSTOL
      COMMON /CPROC/ IREORD(3)
      CHARACTER*1 IREORD

      COMMON /TRANS/ X1,X2,XD,Y1,Y2,YD,Z1,Z2,ZD,NX,NY,NZ,XORG,YORG,
     X   ANGXAX,ZRAD,AZLOW,BAD,ASNF,ACSF,IAXORD(3),NPLANE,EDIAM
      COMMON /SETAZM/ USAZ1,USAZ2,USGAP,USINC,IFOR36,IFORDR
      COMMON /AZSUB/ AT1,AT2,IFLAG,IFLADJ
      COMMON /FORMAT/ IRP,IBLOCK
      COMMON /SCAN/ ICOPLANE,IFLGBAS,IPPI

      COMMON /BYTORD/ MBYTE
 
      DATA NCARD,DASANG/0,-999.0/
 
      DATA IPR/6/
      DATA LSKS / 'INPUT','OUTPUT','RESET','AZIMUTH',
     X            'INTERP','GRID    ','PROCESS','QUIT',
     X            'GRIDXYZ','GRIDCPL','GRIDPPI','RADAR','ANALYT',
     X            'FXTABLE','FLTERTH','FILTER'/
      DATA IFLAT/0/
 
C
C     OUTPUT VERSION AND COPYRIGHT INFO
C
      CALL VERSOUT

      ISKP=0
      IFLAG=0
      AT1=0.0
      AT2=0.0
      IFLADJ=0
      AZCOR=0.0
      IAZFLG=0
      FNUM=0
      NUMFILT=0

C     DEFINE SIGNALS TO BE CATCHED.
      CALL TRAP_SIGNALS()
C
C     GET BYTE ORDERING USED BY MACHINE SPRINT IS RUNNING ON
C
      CALL CBYTE(MBYTE)
      CALL INITAL(ICRTST,INPTST)
C
C        READ NEXT COMMAND
C
 100  CONTINUE
      CALL KARDIN(KRD)
      NCARD=NCARD+1
      READ (KRD,102)KOMM
 102  FORMAT (A7)
      IGO=LOCATEC(KOMM,LSKS,NKOM)
      IF (IGO.LT.1 .OR. IGO.GT.NKOM) GOTO 120
      GOTO (150,160,170,180,200,210,220,300,210,210,210,240,250,260,
     X      270,280),IGO
 120  CONTINUE
      PRINT 103,KOMM
 103  FORMAT (5X,'***UNRECOGNIZABLE COMMAND -- ',A3)
      STOP
 150  CONTINUE
      CALL INPFIL(KRD,INPTST,IAZFLG,AZCOR)
      GOTO 100
 160  CONTINUE
      CALL OUTFIL(KRD)
      GOTO 100
 170  CONTINUE
      CALL RNGFIL(KRD)
      GOTO 100
 180  CONTINUE
      CALL AZMFIL(KRD,AZCOR,IAZFLG,DASANG)
      GOTO 100
 200  CONTINUE
      CALL INTERP(KRD,TFIELD,TLIMITS,NTHRSH,ISIDE)
      GOTO 100
 210  CONTINUE
      CALL CRTSET(KRD,MAXPLN,MXCRT,ICRTST,MAXYZ)
C
C     REMEMBER ORIG. X,Y, AND Z GRID LAYOUT FOR USE WITH RHI SCANS
C
      NDX=NX
      NDY=NY
      NDZ=NZ
      GOTO 100
 220  CONTINUE
      CALL PROFIL(KRD)
      NUFST=0
      IF (ISKP.GT.0 .AND. IRP.NE.2) THEN
C
C     SKIP VOLUMES ON INPUT UNIT BEFORE PROCESSING
C
         IF (IRP.EQ.1) ISKP=ISKP+1
         CALL SKPVOL(IUN,ISKP)
         ISKP=0
      ELSE IF (ISKP.GT.0 .AND. IRP.EQ.2) THEN
         WRITE(*,*)'***SKIPPING DORADE VOLUMES NOT YET ENABLED***'
      END IF
 225  CONTINUE
C
C     I HAVE NO IDEA WHY THE FOLLOWING TWO LINES ARE IN HERE. WDA
C
      IBLV(1,10300,1)=-997
      IBLV(2,10300,1)=-997

C     FOLLOWING LINE IS TEMPORARY; FOR NOW, DORADE FORMAT IMPLIES
C     AIRBORNE SCANS. IN FUTURE, DORADE FORMAT MAY BE USED FOR
C     GROUND BASED SCANS. 
      IF (IRP.EQ.2) ICOPLANE=5
      IF (IRP.EQ.0) THEN
         CALL UFNCAR(NUFST,IBLV,ICOB,ICRTST,NTHRSH,
     X               TFIELD,TLIMITS,RFNAM,FNUM,P1,P2,P3,P4,P10,AZCOR,
     X               DASANG,ISIDE)
      ELSE IF (IRP.EQ.1) THEN
         CALL RPNCAR(NUFST,IBLV,ICOB,ICRTST,CTDBM,CTDBMXH,CTDBMXV,
     X               NTHRSH,TFIELD,TLIMITS,RFNAM,FNUM,P1,P2,P3,P4,P10,
     X               AZCOR,DASANG,ISIDE)
      ELSE IF (IRP.EQ.2) THEN
         CALL DORVOL(NUFST,IBLV,ICOB,ICRTST,CTDBM,CTDBMXH,CTDBMXV,
     X               NTHRSH,TFIELD,TLIMITS,RFNAM,FNUM,P1,P2,P3,P4,P10,
     X               AZCOR,DASANG,ISIDE)

      ELSE
         WRITE(*,*)'***INVALID DATA FORMAT IN UFCART***'
         STOP
      END IF
      IF (NUFST.NE.0) GOTO 228
      CALL METHOD(IPR)
      CALL INHSUM(IPR,'-','Y',AZCOR,DASANG)
      IF (ICOPLANE.EQ.0 .OR. ICOPLANE.EQ.3) THEN
         CALL CRTOUT(ICART,ICTAB,MAXPLN,ICRTST,INPTST,0)
      ELSE IF (ICOPLANE.EQ.1 .OR. ICOPLANE.EQ.2) THEN
         CALL CRTTCP(ICART,ICTAB,MAXPLN,ICRTST,INPTST)
      ELSE IF (ICOPLANE.EQ.4) THEN
         CALL CRTOUT(ICART2,ICTAB2,MAXPLN,ICRTST,INPTST,1)
         CALL CRTOUT(ICART,ICTAB,MAXPLN,ICRTST,INPTST,2)
      ELSE IF (ICOPLANE.EQ.5) THEN
         CALL CRTOUT(ICART,ICTAB,MAXPLN,ICRTST,INPTST,3)
      END IF
C
C     DO FILTERING
C
      IF (NUMFILT.GT.0) THEN
         CALL DOFILT(IBLV,IFLDS,OFLDS,IFLTYP,IPROC,FSPACE,C3,C4,
     X               NSCTP,NUMFILT,ICOPLANE,ICART,NRCBF,MAXPLN,MXCRT,
     X               IFLAT,ICTAB,DASANG,IFLTALL)
      END IF
C
C           CALL INTERPOLATION ROUTINE
C
      IF (ICOPLANE.NE.5 .AND. IPPI.EQ.0) THEN
         CALL TRPVOL(ICART,ICTAB,MAXPLN,ICOB,NDX,NDY,NDZ,ZRTAB,
     X        MXCRT,IBLV,NRCBF,NST,DASANG,IFLAT,NUMFILT,XRTAB,
     X        IVREF)
      IF (NST.NE.0) GOTO 227
      ELSE IF (ICOPLANE.EQ.5) THEN
         CALL TRPARVOL(ICART,ICTAB,MAXPLN,ICOB,NDX,NDY,NDZ,ZRTAB,
     X        MXCRT,IBLV,NRCBF,NST,DASANG,IFLAT,NUMFILT,XRTAB,
     X        IVREF)
      ELSE IF (IPPI.EQ.1) THEN
         CALL TRPPPI(ICART,ICTAB,MAXPLN,ICOB,NDX,NDY,NDZ,ZRTAB,
     X        MXCRT,IBLV,NRCBF,NST,DASANG,IFLAT,NUMFILT,XRTAB,
     X        IVREF)
      END IF
      IF (ICOPLANE.EQ.4) THEN
C
C     IF RHI, SWITCH BACK AXES
C
         NT=NX
         NX=NZ
         NZ=NY
         NY=NT

         T1=X1
         T2=X2
         TD=XD

         X1=Z1
         X2=Z2
         XD=ZD
         
         Z1=Y1
         Z2=Y2
         ZD=YD

         Y1=T1
         Y2=T2
         YD=TD

         TORG=XORG
         XORG=ZRAD
         ZRAD=YORG
         YORG=TORG
      END IF

      CALL CARTAP(IPR,IREORD,ICOB,NX,NY,NZ,IBLV(1,1,1),IBLV(1,1,2),NST,
     X            DASANG)
      IF (NST.NE.0) STOP 7701
 227  CONTINUE
      IF (NUFST.EQ.0) GOTO 225
 228  CONTINUE
      GOTO 100
C
C        OTHER COMMANDS
C
 240  CONTINUE
      CALL RADAR(KRD,CTDBM,CTDBMXH,CTDBMXV)
      GOTO 100
 250  CONTINUE
      CALL ANALYT(KRD,RFNAM,FNAM,FNUM,P1,P2,P3,P4,P10)
      GOTO 100
 260  CONTINUE
      CALL FXTABLE(KRD)
      GOTO 100
 270  CONTINUE
      CALL FLAT(KRD,IFLAT)
      GOTO 100
 280  CONTINUE
      CALL FILTER(KRD,IFLDS,OFLDS,IFLTYP,IPROC,FSPACE,C3,C4,NSCTP,
     X            NUMFILT,IFLTALL)
      GOTO 100
 300  CONTINUE
      PRINT 301
 301  FORMAT (5X,'---QUIT CARD ENCOUNTERED---')
      CALL CCLOSE
      STOP
      END
